# Generated by Django 3.1.4 on 2020-12-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joblisting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('qualifications', models.CharField(max_length=60)),
                ('jobs', models.CharField(choices=[('python_developer', 'PYTHON_DEVELOPER'), ('frontend_developer', 'FRONTEND_DEVELOPER'), ('backend_developer', 'BACKEND_DEVELOPER')], default='python_developer', max_length=50)),
            ],
        ),
    ]
